#If anything is added later use "conda env update -f environment.yml --prune" to change to updated one#
name: MLProject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy         
  - matplotlib
  - seaborn
  - pandas
  - sympy         
  - jupyter  
  - pip
  - pip:
    - torch
    - scikit-learn